### ISSUE TITLE
forge authorize character limit

### ISSUE THREAD

**Issue by philip** [svenluijten/forge-cli#13]
This is strange but here goes.

Upon entering `forge authorize` it appears the maximum allowed value is around 1024 characters. If I enter more characters then it beeps. All additional key presses (included Enter) causes more beeps. Only ^c exits this beepfest.

What might cause this behavior? I'm on macOS. The workaround is to manually insert the token value into `~/forge.json`, a token value that's around 1076 characters.

**Comment by svenluijten** [comment]
Interesting! As I'm using [`symfony/console`](https://github.com/symfony/console), my first guess would be that it's an issue on that repository. I'll do some further research soon.

**Comment by edalzell** [comment]
What is that file supposed to look like, I'm encountering the same issue.

**Comment by svenluijten** [comment]
It's supposed to look like this @edalzell:

```json
{
  "key": "<your Forge key here>"
}
```

I suppose for now you can manually set it.

**Comment by svenluijten** [comment]
Chiming in to say that I'm running into the same issue on macOS (now that I have the opportunity/time to look into it). Will investigate further!

**Comment by ghost** [comment]
Any update on this? I ran into the same issue today.

Re-reading the thread, I'm glad the OP also managed a workaround, but still it would be nice if this issue could somehow be resolved 🤷‍♂ .

**Comment by svenluijten** [comment]
As mentioned in #39, I just merged #41 and [tagged `v0.5.0`](https://github.com/svenluijten/forge-cli/releases/tag/v0.5.0) with some potential fixes. @philip & @Yoeriwalstra can you verify this fixed the issue?

**Comment by ghost** [comment]
Hi sven,

I discontinued using your `forge-cli` package in favor of the Forge API, but I'm happy to hear that you managed to fix the previously encountered issue and I hope it helps people who wish to use your package in the future :).

Kind regards,

**Comment by nvahalik** [comment]
The latest fixes do not appear to fix the issue. However, just running `forge authorize <key>` worked for me.

**Comment by svenluijten** [comment]
Gonna go ahead and close this issue as there's unfortunately not much we can do, it's an upstream issue in the `symfony/console` dependency. 

The "workaround" by doing `forge authorize <key>` works, and if you're not comfortable with that you can always create `~/.forge.json` with `{"key": "<your key here>"}` manually.
