### ISSUE TITLE
make:server error "The given data failed to pass validation."

### ISSUE THREAD

**Issue by j-greig** [svenluijten/forge-cli#19]
Trying to spin up a Linode and get: 

`In MakesHttpRequests.php line 90:
  The given data failed to pass validation.`

With these settings:
`forge make:server --provider=linode --credentials=12345 --region=london --ip=127.0.0.1 --private-ip=192.168.1.1
--php=php71 --database=mysql`

**Comment by svenluijten** [comment]
Hiya James!

The `--ip` and `--private-ip` options are only required when using `--provider=custom`. Can you try without those two and see if this helps? 

(also, I assume you've already added Linode credentials and are using the right ID in the command there? 🙂)

**Comment by j-greig** [comment]
Thanks! I just tried it like this but get the same error?

`forge make:server --provider=linode --credentials=12345 --region=london --php=php71 --database=mysql```

**Comment by svenluijten** [comment]
Looks like you need to use `--region=7` when creating a server on Linode: 

![screenshot](https://i.imgur.com/1uLLBKS.png)

Also; can you run `forge credentials`? Are you using the ID of the one where the "type" is `Linode`?

This package should really do a better job validating the request that's being made; I'll put that on my todo list 😄 For now though, you can see most of the valid options in Laravel Forge's API documentation [here](https://forge.laravel.com/api-documentation).

**Comment by j-greig** [comment]
My bad, I didn't think to look at the Forge API details. Will test on Monday and let you know, think this will work now though 🌮

**Comment by svenluijten** [comment]
No worries, I wouldn't expect users of this package to go looking at some first-party API documentation honestly 👍 

Did you get it working? If not, I'll do some further digging to get this figured out 😄

**Comment by j-greig** [comment]
Can you remind me what `forge.json` should look like if I'm manually creating the file?

**Comment by j-greig** [comment]
Ok time for an update! It's still not working I'm afraid, same error from this:

`forge make:server --provider=linode --credentials=XXXXX --region=7 --php=php71 --database=mysql`

where XXXXX matches an ID from `forge credentials` with type `linode`

**Comment by nvahalik** [comment]
@j-greig I know this is an old issue, but the problem I had was that the `size` and `name` parameters were not set up correctly.

I've submitted a PR which addresses this: #44

**Comment by svenluijten** [comment]
Closing because I am abandoning this package in favor of [`laravel/forge-cli`](https://github.com/laravel/forge-cli).
