### ISSUE TITLE
Support optional wait parameter

### ISSUE THREAD

**Issue by thoresuenert** [svenluijten/forge-cli#23]
We want to use this package to deploy from command line in ci, so we have to do multiple steps in the right order.
To do this we need to wait for everything ;)

We need to bump the sdk to v2 for that (https://github.com/svenluijten/forge-cli/pull/20)

We will add `$wait` as an optional parameter where possible and use the default value from the sdk itself.

**Comment by svenluijten** [comment]
Hey @thoresuenert, thanks for your interest in this package! I'm sort of short on time to properly maintain this package (and it's not even reached `v1.0.0` yet). 

I'll take a look at this whenever I can, or if you want you can submit a(nother) PR, which I'll happily merge! 🙂

**Comment by thoresuenert** [comment]
@svenluijten  pr we go :P

**Comment by svenluijten** [comment]
Closing because I am abandoning this package in favor of [`laravel/forge-cli`](https://github.com/laravel/forge-cli).
