### ISSUE TITLE
Force flags for non interactive use

### ISSUE THREAD

**Issue by thoresuenert** [svenluijten/forge-cli#25]
We use this client in a github action to setup a review app when pr is opened.

Some Commands are interactive especially the `delete` ones.

It would be nice to have a `--force` to use any command in an non-interactive way.

@svenluijten if you accept this i will come up with a PR.

**Comment by svenluijten** [comment]
100% agree, would welcome a PR with this!

**Comment by svenluijten** [comment]
Closing because I am abandoning this package in favor of [`laravel/forge-cli`](https://github.com/laravel/forge-cli).
