### ISSUE TITLE
Rename commands to `class:action`

### ISSUE THREAD

**Issue by thoresuenert** [svenluijten/forge-cli#26]
The command output is hard to scan.
Does it make sense to go with the following for example: 

instead of 
```
install
 install:certificate
 install:git
```

go with

```
certificate
  certificate:install
  certificate:list
```

for creating things we can go the laravel route and prefix it with make

```
make
  make:site
  make:certificate
```

Just a start for a conversation, i am not sure right now which could be the best way to sort stuff.
The confusing stuff for me is some commands are only for servers others for sites etc.

**Comment by svenluijten** [comment]
Yeah, this is definitely something I struggled with when setting up the package initially. I do agree that it's hard to scan as it is now, but I wanted to keep it "Laravel-y", so went with `action:resource` (in line with `make:controller` etc.).

It wouldn't make sense (in my opinion) to add `make:site`, and then `site:deploy` or something, this would fragment the whole setup. I _guess_ we could make it a configuration option somehow? 🤔

**Comment by thoresuenert** [comment]
@svenluijten i would argue against :D 

laravel-ish would be:
```
make
  make:migration

migration
  migration:fresh
  migration:install
```
