### ISSUE TITLE
How does the certificate thing should be implemented?

### ISSUE THREAD

**Issue by thoresuenert** [svenluijten/forge-cli#27]
The update to `themsaid/forge-sdk@v2` changed function signatures and i tried to fix it with passing `[]` which results in errors.

The [API Docs](https://forge.laravel.com/api-documentation#ssl-certificates) are not really clear to me which endpoint provide what kind of functionality.

which functionality do we want to provide? all of them?
What is the exact difference between create and install?

I try to install/acticate an extisting wildcard certificate on a new site but dont know how to do it right now.

We provide the following endpoint with arguments: `server_id`, `site_id`, `certificate_id`
https://forge.laravel.com/api-documentation#install-certificate
 The payload leads to the question: What does this endpoint actually do?

**Comment by svenluijten** [comment]
Honestly I've never worked with certificates that wasn't with something as simple as LetsEncrypt, so I don't know 😕 

This might be something to [create an issue in `themsaid/forge-sdk`](https://github.com/themsaid/forge-sdk/issues/new) for? AFAIK Mohamed also maintains Forge itself, so he should be able to provide more details.

**Comment by svenluijten** [comment]
Closing because I am abandoning this package in favor of [`laravel/forge-cli`](https://github.com/laravel/forge-cli).
