### ISSUE TITLE
return site id when making a new site

### ISSUE THREAD

**Issue by sebszocinski** [svenluijten/forge-cli#43]
We're trying to automate a deployment bash script that makes a new site, installs a repo and then runs deployments.

Currently we need to do some manual work to provide the site id after we create it. Is there any output the id or save it to a config file?

**Comment by nvahalik** [comment]
There is not, but you can run a script like this to grab the site ID/IP:

```bash
SERVER_ID=$(forge server:list | grep <my-server-name> | cut -f 3 -d'|' | sed -e 's/^[[:space:]]*//'  -e 's/[[:space:]]*$//')
SERVER_IP=$(forge server:list | grep <my-server-name> | cut -f 4 -d'|' | sed -e 's/^[[:space:]]*//'  -e 's/[[:space:]]*$//')
```

Note that these work alongside this PR: #44.

**Comment by svenluijten** [comment]
Closing because I am abandoning this package in favor of [`laravel/forge-cli`](https://github.com/laravel/forge-cli).
