### ISSUE TITLE
Should `create:*` commands be renamed to `make:*`?

### ISSUE THREAD

**Issue by svenluijten** [svenluijten/forge-cli#5]
```bash
# So should this:
$ forge create:server --name=something --provider=ocean2
# be renamed to this:
$ forge make:server --name=something --provider=ocean2
```

It would make sense, since Laravel follows the `make:*` schema as well, but I'm a bit torn on this. `create` just sounds a bit more descriptive and resolute.

**Comment by sepehr** [comment]
Easier to type and more laravelish, why not?

**Comment by svenluijten** [comment]
Yep that's the reason I asked! I will get on it whenever I can find some time, which as of lately hasn't been easy 😞 Unless you'd want to PR it in for me? 👼

**Comment by sepehr** [comment]
😆  Will surely do, Sven! But as soon as I'm done with the forthcoming deadline.

**Comment by sepehr** [comment]
Seems like that I never did. Shame :(

**Comment by svenluijten** [comment]
haha, no worries! I was working on this repo and figured I'd pick it up 🙂
