### ISSUE TITLE
PHP 7.4 breaks commands

### ISSUE THREAD

**Issue by sebszocinski** [svenluijten/forge-cli#50]
I've only tested `env:set` but i'm getting this error:

```
In BaseCommand.php line 102:
This command requires either the "--file" option to be set, or an input from STDIN. 
```

The command i'm using is:
`forge env:set --file=.env.staging XXXXX XXXXXX`

**Comment by svenluijten** [comment]
Closing because I am abandoning this package in favor of [`laravel/forge-cli`](https://github.com/laravel/forge-cli).
